package com.duobaoyu.mybatis.mapper;

import com.duobaoyu.mybatis.entity.AccountTbl;
import java.util.List;

public interface AccountTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated Thu Nov 26 22:55:10 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated Thu Nov 26 22:55:10 CST 2020
     */
    int insert(AccountTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated Thu Nov 26 22:55:10 CST 2020
     */
    AccountTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated Thu Nov 26 22:55:10 CST 2020
     */
    List<AccountTbl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated Thu Nov 26 22:55:10 CST 2020
     */
    int updateByPrimaryKey(AccountTbl record);

    int debit(String userId,Integer money);
}