package com.duobaoyu.mybatis.mapper;

import com.duobaoyu.mybatis.entity.OrderTbl;
import java.util.List;

public interface OrderTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    int insert(OrderTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    OrderTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    List<OrderTbl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    int updateByPrimaryKey(OrderTbl record);
}