package com.duobaoyu.mybatis.mapper;

import com.duobaoyu.mybatis.entity.StorageTbl;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StorageTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Nov 26 22:51:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Nov 26 22:51:26 CST 2020
     */
    int insert(StorageTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Nov 26 22:51:26 CST 2020
     */
    StorageTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Nov 26 22:51:26 CST 2020
     */
    List<StorageTbl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated Thu Nov 26 22:51:26 CST 2020
     */
    int updateByPrimaryKey(StorageTbl record);

    int deduct(@Param("commodityCode") String commodityCode, @Param("num") Integer count);
}