package com.duobaoyu.seata.model;

import lombok.Data;

/**
 * @author FS001338
 * @date 2020/11/27
 */
@Data
public class Order {
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.id
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.user_id
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.commodity_code
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private String commodityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.count
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.money
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private Integer money;
}
