package com.duobaoyu.mybatis.entity;

public class OrderTbl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.id
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.user_id
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.commodity_code
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private String commodityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.count
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_tbl.money
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.id
     *
     * @return the value of order_tbl.id
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.id
     *
     * @param id the value for order_tbl.id
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.user_id
     *
     * @return the value of order_tbl.user_id
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.user_id
     *
     * @param userId the value for order_tbl.user_id
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.commodity_code
     *
     * @return the value of order_tbl.commodity_code
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.commodity_code
     *
     * @param commodityCode the value for order_tbl.commodity_code
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.count
     *
     * @return the value of order_tbl.count
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.count
     *
     * @param count the value for order_tbl.count
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_tbl.money
     *
     * @return the value of order_tbl.money
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_tbl.money
     *
     * @param money the value for order_tbl.money
     *
     * @mbg.generated Thu Nov 26 22:53:37 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}